### ISSUE TITLE
Stop using env within the middleware, pass through params?

### ISSUE THREAD

**Issue by jbrooksuk** [DivineOmega/laravel-route-restrictor#3]
Why not pass through the username and password combination as a middleware config option? The middleware shouldn't be calling the `env` method.

If you want to retain the "global" config too, you could publish a config file (then use the Config contract) to store these. The config itself _can_ use the `env` result.

**Comment by jbrooksuk** [comment]
I'll do this if/when #2 is merged as it provides a better foundation to do so.

**Comment by jbrooksuk** [comment]
In fact, like @vinkla's package :) https://github.com/vinkla/shield

**Comment by Jord-JD** [comment]
> If you want to retain the "global" config too, you could publish a config file (then use the Config contract) to store these. The config itself can use the env result.

I like this idea, as the main use case I've had for the package is to globally restrict a site for live demonstrations, but leave it open for local development work.

**Comment by vinkla** [comment]
@DivineOmega You can do that with Laravel Shield if you want :)

**Comment by Jord-JD** [comment]
@jbrooksuk If you still want to do this, please feel free. #2 has now been merged. :)

**Comment by Jord-JD** [comment]
This is done in the v2.0.0 release.
